# Generated by Django 5.0.7 on 2024-07-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titel',
            new_name='title',
        ),
    ]
